version: 2.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 92tF47KjBR7PvZKHSvOyde7y5i17Ciwai1+X4gVtNKqGEK1ZrVl8EHQkatu/BjcH
  skip_symbols: true
  on:
    branch: master